FROM nvidia/cuda:12.4.1-cudnn8-runtime-ubuntu22.04
RUN apt-get update && apt-get install -y --no-install-recommends python3.11 python3-pip && rm -rf /var/lib/apt/lists/*
RUN python3.11 -m pip install --upgrade pip && pip install torch --index-url https://download.pytorch.org/whl/cu124
WORKDIR /workspace
CMD ["python3.11"]
